# Generated by Django 2.2 on 2020-08-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='GRUPO')),
            ],
        ),
        migrations.CreateModel(
            name='PadreTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_apaterno', models.CharField(max_length=200, verbose_name='A. Paterno')),
                ('parent_amaterno', models.CharField(default='', max_length=200, verbose_name='A. Materno')),
                ('parent_nombre', models.CharField(default='', max_length=200, verbose_name='Nombre(s)')),
                ('parent_curp', models.CharField(max_length=200, unique=True, verbose_name='CURP')),
                ('parent_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('parentesco', models.CharField(max_length=100, verbose_name='Parentesco')),
                ('parent_domicilio', models.TextField(verbose_name='Domicilio')),
                ('folio', models.CharField(blank=True, max_length=40, null=True, verbose_name='Folio')),
                ('tutela', models.BooleanField(default=True)),
                ('dateadd', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=300)),
                ('location', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/pupils/')),
                ('apaterno', models.CharField(max_length=200, verbose_name='Apellido Paterno')),
                ('amaterno', models.CharField(default='', max_length=200, verbose_name='Apellido Materno')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre(s)')),
                ('curp', models.CharField(max_length=200, unique=True, verbose_name='CURP')),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10, verbose_name='Sexo')),
                ('nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('lugar_nacimeinto', models.CharField(max_length=500, verbose_name='Lugar nacimeinto')),
                ('domicilio', models.TextField(verbose_name='Domicilio')),
                ('peso', models.CharField(max_length=10, verbose_name='Peso')),
                ('medida', models.CharField(max_length=10, verbose_name='Medida')),
                ('tipo_desangre', models.CharField(max_length=10, verbose_name='Tipo de Sangre')),
                ('otra_escuela', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ha asistido a otra escuela')),
                ('peso_al_nacer', models.CharField(blank=True, max_length=10, null=True, verbose_name='¿Cuánto peso al nacer?')),
                ('talla_al_nacer', models.CharField(blank=True, max_length=10, null=True, verbose_name='¿Cuánto midio al nacer?')),
                ('enfermedad_cronica', models.CharField(blank=True, max_length=500, null=True, verbose_name='¿Tiene alguna enfermedad Crónica? ¿Cuál?')),
                ('alergias', models.CharField(blank=True, max_length=500, null=True, verbose_name='¿Es alérgico a algo?')),
                ('goples', models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Sufrió algun golpe en la cabeza?')),
                ('alimentacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Come todo tipo de alimentos?')),
                ('esfinteres', models.CharField(choices=[('no', 'aun no'), ('dia', 'de dia'), ('noche', 'de noche'), ('ambos', 'ambos')], max_length=100, verbose_name='Controla  esfinteres')),
                ('actividades_familiares', models.CharField(blank=True, max_length=500, null=True, verbose_name='¿Qué actividades realiza en familia?')),
                ('comportameinto_en_casa', models.CharField(blank=True, max_length=500, null=True, verbose_name='¿Cómo describiria el comportamiento del niño(a) en casa?')),
                ('castigos', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Castigan al niño?')),
                ('juegos_habituales', models.CharField(blank=True, max_length=500, null=True, verbose_name='¿A qué juega habitualmente?')),
                ('seguir_reglas', models.CharField(blank=True, max_length=200, null=True, verbose_name='¿Qué tanto se adapta a las reglas del juego?')),
                ('tiempo_tv_tablet', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Cuánto tiempo ve televisión, internet o algun otro tipo de entretenimiento?')),
                ('se_viste', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Se viste solo o quien lo ayuda?')),
                ('tutela', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tutela del menor ')),
                ('registro', models.DateField(auto_now_add=True)),
                ('folio', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('grado', models.ForeignKey(on_delete='Grado al que se inscribe', to='direction.Grado')),
                ('parenttutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='direction.PadreTutor')),
            ],
        ),
    ]
