# Generated by Django 2.2 on 2020-07-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
