# Generated by Django 2.2 on 2020-08-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='padretutor',
            name='parent_amaterno',
            field=models.CharField(default='', max_length=200, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='padretutor',
            name='parent_apaterno',
            field=models.CharField(max_length=200, verbose_name='Apellido Paterno'),
        ),
    ]
