# Generated by Django 2.2 on 2020-07-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0002_delete_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='folio',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='medida',
            field=models.CharField(max_length=10, verbose_name='Medida'),
        ),
    ]
