# Generated by Django 2.2 on 2020-03-19 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_prof', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/profs')),
                ('useras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('mid_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('yob', models.IntegerField()),
                ('dof', models.DateField()),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pre', max_length=20)),
                ('contact_info', models.TextField(default='')),
                ('foto', models.ImageField(upload_to='static/pupils/')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=300)),
                ('location', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=10)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='PupilHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('descp', models.TextField()),
                ('pupilh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Pupil')),
            ],
        ),
        migrations.AddField(
            model_name='pupil',
            name='cur_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.SchoolGroup'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='parents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
