# Generated by Django 2.2 on 2020-05-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200319_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='useras',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='cur_group',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='pupilhistory',
            name='pupilh',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.RemoveField(
            model_name='schoolgroup',
            name='prof',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Pupil',
        ),
        migrations.DeleteModel(
            name='PupilHistory',
        ),
        migrations.DeleteModel(
            name='SchoolGroup',
        ),
    ]
